version: '2.1'
services:
  spotify-radio:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command: 
      - npm
      - run
      - dev
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules: {}