version: '2.1'
services:
  spotify-radio:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command: 
      - npm
      - run
      - dev
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

  test:
    image: spotify-radio
    build: .
    command: 
      - npm
      - run
      - test
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

  test-watch:
    image: spotify-radio
    build: .
    command: 
      - npm
      - run
      - test-watch
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

  test-coverage:
    image: spotify-radio
    build: .
    command: 
      - npm
      - run
      - test-coverage
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: {}